version: '2'

services:
    website:
        build:
            context: .
        command: yarn dev
        ports:
            - 8888:80
        volumes:
            - .:/usr/src/app
            
networks:
    default:
        external:
            name: nginx-proxy-example